"""add_processed_documents_table

Revision ID: 16809c6b8ddf
Revises: a6a0a395ae93
Create Date: 2026-07-20 09:31:43.182057
"""
from alembic import op
import sqlalchemy as sa


revision = '16809c6b8ddf'
down_revision = 'a6a0a395ae93'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attachment_id', sa.UUID(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('processing_method', sa.String(), nullable=False),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attachment_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_documents')
    # ### end Alembic commands ###
